### ISSUE TITLE
大概什么时候能在线预览？

### ISSUE THREAD

**Issue by whevether** [jdf2e/nutui-react-native#1]
大概什么时候能在线预览。并达到可用状态。有计划吗?

**Comment by StarHosea** [comment]
+1 期待

**Comment by soulhat** [comment]
> 大概什么时候能在线预览。并达到可用状态。有计划吗?
目前正在做最后的文档整理和验证，可以通过下面方式进行体验 Demo 效果：
`yarn install`
`yarn dev`

**Comment by soulhat** [comment]
体验过程中有问题，欢迎多反馈哈 👏👏👏

**Comment by whevether** [comment]
> 体验过程中有问题，欢迎多反馈哈 👏👏👏

好的。可以加入贡献吗? 如果可以要怎么加入贡献呀

**Comment by soulhat** [comment]
> > 体验过程中有问题，欢迎多反馈哈 👏👏👏
> 
> 好的。可以加入贡献吗? 如果可以要怎么加入贡献呀

可以的，欢迎提交 PR，等第一版文档齐全了，我们也会开放后面更新和迭代计划，到时候可以一起参与
