### ISSUE TITLE
项目跑不起来

### ISSUE THREAD

**Issue by quarkcms** [jdf2e/nutui-react-native#2]
![image](https://user-images.githubusercontent.com/60868863/222860570-39e5a927-93ed-43ba-a06b-c7f577f189b2.png)
项目跑不起来，报错

**Comment by soulhat** [comment]
> ![image](https://user-images.githubusercontent.com/60868863/222860570-39e5a927-93ed-43ba-a06b-c7f577f189b2.png) 项目跑不起来，报错

Node 版本 > 16 ，请参考如下 issue 解决：
[expo start --web fails "error:03000086:digital envelope routines::initialization error"](https://github.com/expo/expo-cli/issues/4037)
[nodejs 17: digital envelope routines::unsupported](https://github.com/webpack/webpack/issues/14532)
