### ISSUE TITLE
组件无法使用

### ISSUE THREAD

**Issue by renjiali** [jdf2e/nutui-react-native#23]
ERROR  [Error: undefined Unable to resolve module expo-linear-gradient from C:\Users\admin\Desktop\project\reacti-native\node_modules\@nutui\nutui-react-native\components\skeleton\skeleton.tsx: expo-linear-gradient could not be found within the project or in these directories:
  node_modules\@nutui\nutui-react-native\node_modules
  node_modules
   5 | import Avatar from '../avatar';
   6 |
>  7 | import * as LinearGradient from 'expo-linear-gradient';
     |                                  ^
   8 |
   9 | import fConStyle from '../utils/filter-container-style';
  10 | import toObj from '../utils/style-to-obj';]

**Comment by lixy01** [comment]
我也碰到这个问题了

**Comment by jamninetyfive** [comment]
resolve: {
    alias: {
        'expo-linear-gradient': 'react-native-linear-gradient',
    }
}

**Comment by soulhat** [comment]
> 非expo项目配置指定下依赖库
> 
> ```
> resolve: {
>     alias: {
>         'expo-linear-gradient': 'react-native-linear-gradient',
>     }
> }
> ```

感谢回答，渐变色这块目前没有太好的解决方案，如果有更好的方案，欢迎讨论。
